# תרגיל מסכם - numpy

### בתרגיל הנוכחי, כמו בכל תרגיל בקורס, אתם צריכים למלא את החסר
 

### תייבאו את הספריה

### תיצרו מערך מהרשימה

In [3]:
lst = [1, 2, 3, 4]
arr = 
arr

array([1, 2, 3, 4])

### תיצרו מערך של 5 אחדות

array([1., 1., 1., 1., 1.])

### תיצרו מערך של 8 אפסים

array([0., 0., 0., 0., 0., 0., 0., 0.])

### תיצרו מערך של 4 חמישיות

array([5., 5., 5., 5.])

### תיצרו מערך של כל המספרים בין 1 ל 15

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### תיצרו מערך של 100 ערכים בין 1 ל 10, עם פיזור שווה

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

### תיצרו מערך דו מימדו מהרשימות

In [11]:
lst_1 = [1, 2, 3]
lst_2 = [4, 5, 6]
lst_3 = [7, 8, 9]
arr_2d = 
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### תיצרו את אותו מערך דו מימדי בלי להשתמש ברשימות

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### תיצרו מספר רנדומלי בין 0 ל 1

0.18749067320414115

### תיצרו מספר שלם רנדומלי בין 1 ל 13

5

### תיצרו מערך דו מימדי בגודל (5,5) של ערכים רנדומליים בין 0 ל 1

array([[0.26342719, 0.51893716, 0.23118637, 0.16355166, 0.63387747],
       [0.3945974 , 0.20418156, 0.5149504 , 0.39833467, 0.84393487],
       [0.09542144, 0.93383238, 0.94384731, 0.75856159, 0.16729223],
       [0.7002629 , 0.83059599, 0.97381555, 0.55961577, 0.3932541 ],
       [0.47753563, 0.47315263, 0.58196552, 0.47761713, 0.13574035]])

### תיצרו את המערך הדו מימדי הבא

In [35]:
arr = 
arr

array([[12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25]])

### תחליפו את הערך 21 ב 44 במערך שיצרתם

In [36]:

arr

array([[12, 13, 14, 15, 16, 17, 18],
       [19, 20, 44, 22, 23, 24, 25]])

### חשבו את הסכום של כל איברי המערך

In [37]:
arr = np.arange(1, 10)
arr_sum = 
arr_sum

45

### החזירו את כל איברי המערך הדו מימדי שגדולים מ 2

In [39]:
arr = np.array([[-1, 4, 2], [3, 3, 3], [1, 2, 8]])


array([4, 3, 3, 3, 8])

### חשבו את הערך של כל איברי המערך בריבוע

In [41]:
arr = np.arange(1, 11)


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### חשבו את ההפרש בין כל זוג איברים תואמים מהמערכים

In [43]:
arr_1 = np.arange(0, 10)
arr_2 = np.arange(10, 20)


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])